### ISSUE TITLE
CORS issues

### ISSUE THREAD

**Issue by Daiz** [Fugiman/diff.pics#8]
```
XMLHttpRequest cannot load http://cdn.diff.pics/FE5D41A13D6A6BF8FF6608EE9642AF71BCF6B9CE.png. Redirect from 'http://cdn.diff.pics/FE5D41A13D6A6BF8FF6608EE9642AF71BCF6B9CE.png' to 'https://cdn.diff.pics/FE5D41A13D6A6BF8FF6608EE9642AF71BCF6B9CE.png' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://diff.pics' is therefore not allowed access.
```

All comparisons are currently failing to load for me with this logged in the console. I've heard this happening to other people in the past too, so something definitely seems to be wrong on the site end here.

(On another note, why is image loading being done with XMLHttpRequest anyway? You could just make `Image` objects in JS code directly and set `src` on them to the image URLs instead, which wouldn't get blocked by CORS.)

**Comment by Fugiman** [comment]
1) Previous CORS issues were a different problem, and were caused by users viewing the image directly, causing it to be cached in cloudfront without CORS headers.
2) This issue was caused by upgrading cdn.diff.pics to use HTTPS so that it can use http2, and should have only lasted a few minutes. This is the first step in a series of performance and stability improvements I have planned for this week.
3) Images are loaded with XHR so that we can generate the "Download" link, as it seemed like an easy way to ensure backwards compatibility. This was a mistake, and will be rectified in aforementioned performance improvements.
